<a href="https://colab.research.google.com/github/Desmondonam/DS_Python/blob/main/working_with_numpy_arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Here is a practcal guide on how to make use of numpy and how it is used.

NumPy is a powerful library in Python for numerical computing, and it provides support for creating and manipulating arrays and matrices. NumPy arrays, known as ndarrays, are the fundamental data structures in NumPy, and they allow you to perform efficient numerical operations on large datasets.

In [2]:
## importingnumpy to use in the notebook
import numpy as np # t

### 2. creating a numpy array

In [3]:
###  you can create it from a python list like this
my_list = [1, 2, 3, 4, 5]
arr = np.array(my_list)

In [5]:
arr

array([1, 2, 3, 4, 5])

In [4]:
## Usinf built in functions
zeros_arr = np.zeros(5)       # Creates an array of zeros with 5 elements
ones_arr = np.ones((3, 4))    # Creates a 3x4 array of ones
random_arr = np.random.rand(3, 2)  # Creates a 3x2 array with random values between 0 and 1

In [6]:
random_arr

array([[0.93017334, 0.63532656],
       [0.42242742, 0.66022189],
       [0.04095534, 0.49453441]])

In [7]:
## Array attributes
arr.shape       # Tuple representing the dimensions of the array (rows, columns)
arr.ndim        # Number of array dimensions (1 for a 1D array, 2 for a 2D array, etc.)
arr.size        # Total number of elements in the array
arr.dtype       # Data type of the array elements

dtype('int64')

In [14]:
## Array indexing and slicing
arr[0]            # Access the first element of the array
arr[1:4]          # Slice elements from index 1 to 3 (exclusive)
arr[::2]          # Select every other element


array([1, 3, 5])

In [15]:
## Array operations
# We can perfom mathematical operation on arrays elements
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

arr_sum = arr1 + arr2      # Element-wise addition
arr_product = arr1 * arr2  # Element-wise multiplication
arr_squared = arr1 ** 2    # Element-wise exponentiation

In [16]:
arr_sum

array([5, 7, 9])

In [17]:
arr_product

array([ 4, 10, 18])

In [18]:
arr_squared

array([1, 4, 9])

In [19]:
## Broadcasting
## Numpy allows operation on different arrays through broadcasting
arr = np.array([[1, 2], [3, 4]])
scalar = 2

result = arr + scalar
# Output:
# array([[3, 4],
#        [5, 6]])

In [20]:
result

array([[3, 4],
       [5, 6]])

In [21]:
## Array aggregation
# you can compute statistics andaggregate along axes
arr.mean()         # Compute the mean of all elements
arr.sum(axis=0)    # Sum elements along axis 0 (columns)
arr.min(axis=1)    # Find the minimum value along axis 1 (rows)
arr.max()          # Find the maximum value in the entire array

4

In [22]:
## redahping
#by using the reshapemethod you can reshape an array
arr = np.array([1, 2, 3, 4, 5, 6])
reshaped_arr = arr.reshape(2, 3)
# Output:
# array([[1, 2, 3],
#        [4, 5, 6]])

In [23]:
reshaped_arr

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
## array concatination and splitting
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6]])

np.concatenate((arr1, arr2), axis=0)
# Output:
# array([[1, 2],
#        [3, 4],
#        [5, 6]])

array([[1, 2],
       [3, 4],
       [5, 6]])

In [25]:
## Array filtering
# you cna use boolean to filter array
arr = np.array([1, 2, 3, 4, 5])
condition = arr > 2

filtered_arr = arr[condition]
# Output: array([3, 4, 5])

In [26]:
filtered_arr

array([3, 4, 5])

NumPy provides many more functionalities for advanced numerical computing, such as matrix operations, linear algebra, and Fourier transforms. It is widely used in scientific and data analysis applications due to its performance and ease of use. For more detailed information, you can refer to the official [NumPy documentation](https://numpy.org/doc/stable/)